//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccentureAcademy.TpFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EscritoPor
    {
        public int Id { get; set; }
        public int Id_Libro { get; set; }
        public int Id_Autor { get; set; }
    
        public virtual Autores Autores { get; set; }
        public virtual Libros Libros { get; set; }
    }
}
